<script src ="{{asset('dist/js/demo-theme.min.js?1692870487')}}"></script>
<script src ="{{asset('dist/js/tabler.min.js?1692870487')}}" defer></script>
<script src = "{{asset('dist/libs/apexcharts/dist/apexcharts.min.js?1692870487')}}" defer></script>
<script src = "{{asset('dist/libs/jsvectormap/dist/js/jsvectormap.min.js?1692870487')}}" defer></script>
<script src = "{{asset('dist/libs/jsvectormap/dist/maps/world.js?1692870487')}}" defer></script>
<script src = "{{asset('dist/libs/jsvectormap/dist/maps/world-merc.js?1692870487')}}" defer></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://cdn.datatables.net/2.1.8/js/dataTables.min.js"></script>